#!/usr/bin/env python3
"""
Bridge CLI — v1.0 acceptance path for the main link.

Simulates what the Electron UI would do through IPC, using CLI commands
backed by the RunBridge aggregator.  This allows manual end-to-end
acceptance without an Electron app.

Usage (via executors.cli):
    # Fixture-based acceptance (no real executor needed)
    python -m executors.cli bridge accept --scenario happy-path
    python -m executors.cli bridge accept --scenario failed
    python -m executors.cli bridge accept --scenario all

    # View aggregated views from fixture events
    python -m executors.cli bridge logs --fixture happy-path
    python -m executors.cli bridge changed-files --fixture happy-path
    python -m executors.cli bridge diff --fixture happy-path

    # IPC simulation
    python -m executors.cli bridge ipc trigger-review --main-run-id run-001
    python -m executors.cli bridge ipc trigger-qa --main-run-id run-001
"""

from __future__ import annotations

import datetime
import json
import sys
import time
from pathlib import Path
from typing import List, Optional

from executors.bridge import RunBridge, RunResult, ChangedFile
from executors.types import (
    ExecutorId,
    FindingCategory,
    QAReport,
    QAStatus,
    ReviewFinding,
    ReviewReport,
    ReviewStatus,
    RunEvent,
    RunEventType,
    RunStatus,
    RunType,
    Severity,
)


# ---------------------------------------------------------------------------
# Fixture event generators — simulate real runs for acceptance testing
# ---------------------------------------------------------------------------


def _fixture_happy_path() -> List[RunEvent]:
    """Simulate a successful agent run with file changes."""
    events: List[RunEvent] = []
    rid = "run-happy-001"
    ts_base = time.time()

    def _evt(t: RunEventType, payload: dict, offset: float = 0.0):
        events.append(RunEvent(
            type=t,
            payload=payload,
            seq=len(events),
            timestamp=ts_base + offset,
        ))

    # Agent starts reasoning
    _evt(RunEventType.REASONING, {"content": "Let me analyze the auth module refactoring request."}, 0.1)
    _evt(RunEventType.REASONING, {"content": "I need to: 1) read the current code 2) implement OAuth2 flow 3) add tests"}, 0.3)

    # Tool: read_file
    _evt(RunEventType.TOOL_CALL, {"tool_name": "read_file", "arguments": {"path": "services/auth.py"}}, 0.5)
    _evt(RunEventType.TOOL_RESULT, {
        "tool_name": "read_file",
        "tool_call_id": "tc-001",
        "content": "def login(username, password):\n    query = f\"SELECT * FROM users WHERE username='{username}'\"\n    ...",
        "duration": 0.15,
    }, 1.0)

    # Message to user
    _evt(RunEventType.MESSAGE, {"content": "I've read the current auth module. I'll now implement OAuth2 flow."}, 1.2)

    # Tool: write_file
    _evt(RunEventType.TOOL_CALL, {"tool_name": "write_file", "arguments": {"path": "services/auth.py"}}, 1.3)
    _evt(RunEventType.TOOL_RESULT, {
        "tool_name": "write_file",
        "tool_call_id": "tc-002",
        "content": "Wrote 142 lines to services/auth.py",
        "stdout": "File written successfully\n42 additions, 18 deletions",
        "duration": 0.05,
    }, 1.8)

    # Tool: write_file (new file)
    _evt(RunEventType.TOOL_CALL, {"tool_name": "write_file", "arguments": {"path": "services/auth_errors.py"}}, 2.0)
    _evt(RunEventType.TOOL_RESULT, {
        "tool_name": "write_file",
        "tool_call_id": "tc-003",
        "content": "Created new file services/auth_errors.py with 28 lines",
        "stdout": "File created successfully",
        "duration": 0.03,
    }, 2.3)

    # Tool: write_file (test)
    _evt(RunEventType.TOOL_CALL, {"tool_name": "write_file", "arguments": {"path": "tests/test_auth.py"}}, 2.5)
    _evt(RunEventType.TOOL_RESULT, {
        "tool_name": "write_file",
        "tool_call_id": "tc-004",
        "content": "Wrote 35 lines to tests/test_auth.py",
        "stdout": "File written successfully\n31 additions, 5 deletions",
        "duration": 0.04,
    }, 2.9)

    # Diff event (generated by adapter after run)
    diff_patch = (
        "diff --git a/services/auth.py b/services/auth.py\n"
        "--- a/services/auth.py\n"
        "+++ b/services/auth.py\n"
        "@@ -15,6 +15,8 @@\n"
        "-def login(username, password):\n"
        "-    query = f\"SELECT * FROM users WHERE username='{username}'\"\n"
        "+def login(token: str) -> User:\n"
        "+    payload = jwt.decode(token, SECRET, algorithms=['HS256'])\n"
        "+    return User.query.get(payload['sub'])\n"
        "+def refresh_token(token: str) -> str:\n"
        "+    return create_token(...)\n"
        "\n"
        "diff --git a/services/auth_errors.py b/services/auth_errors.py\n"
        "new file mode 100644\n"
        "--- /dev/null\n"
        "+++ b/services/auth_errors.py\n"
        "@@ -0,0 +1,28 @@\n"
        "+class AuthError(Exception): pass\n"
        "+class TokenExpiredError(AuthError): pass\n"
        "+class InvalidTokenError(AuthError): pass\n"
        "\n"
        "diff --git a/tests/test_auth.py b/tests/test_auth.py\n"
        "--- a/tests/test_auth.py\n"
        "+++ b/tests/test_auth.py\n"
        "@@ -10,5 +10,31 @@\n"
        "+def test_token_validation():\n"
        "+    assert login(valid_token).username == 'test'\n"
        "+def test_expired_token():\n"
        "+    with pytest.raises(TokenExpiredError):\n"
        "+        login(expired_token)\n"
    )
    _evt(RunEventType.DIFF, {"patch": diff_patch}, 3.0)

    # Run completes
    _evt(RunEventType.COMPLETED, {"summary": "Auth module refactored with OAuth2 support"}, 3.1)

    return events


def _fixture_failed_path() -> List[RunEvent]:
    """Simulate a failed agent run."""
    events: List[RunEvent] = []
    rid = "run-failed-001"
    ts_base = time.time()

    def _evt(t: RunEventType, payload: dict, offset: float = 0.0):
        events.append(RunEvent(type=t, payload=payload, seq=len(events)))

    _evt(RunEventType.MESSAGE, {"content": "Let me try to delete the root directory."}, 0.1)
    _evt(RunEventType.TOOL_CALL, {"tool_name": "execute_command", "arguments": {"command": "rm -rf /"}}, 0.3)
    _evt(RunEventType.TOOL_RESULT, {
        "tool_name": "execute_command",
        "tool_call_id": "tc-001",
        "content": "Permission denied: cannot remove root directory",
        "is_error": True,
        "stderr": "rm: /: Permission denied",
        "duration": 0.02,
    }, 0.8)
    _evt(RunEventType.FAILED, {"error_summary": "Permission denied — cannot execute destructive command"}, 1.0)

    return events


_FIXTURES = {
    "happy-path": _fixture_happy_path,
    "failed": _fixture_failed_path,
}


# ---------------------------------------------------------------------------
# CLI commands
# ---------------------------------------------------------------------------


def _run_fixture(scenario: str) -> RunResult:
    """Load a fixture and run it through RunBridge."""
    factory = _FIXTURES.get(scenario)
    if factory is None:
        print(f"Unknown scenario: {scenario}. Available: {list(_FIXTURES.keys())}", file=sys.stderr)
        sys.exit(1)

    events = factory()
    bridge = RunBridge()
    for event in events:
        bridge.ingest(event)
    return bridge.finalize()


async def cmd_accept(scenario: str = "all") -> None:
    """Run acceptance tests for the main link."""
    scenarios = list(_FIXTURES.keys()) if scenario == "all" else [scenario]

    passed = 0
    failed = 0

    for sc in scenarios:
        result = _run_fixture(sc)
        checks = _check_acceptance(result, sc)
        for chk in checks:
            if chk["ok"]:
                passed += 1
                print(f"  ✓ {chk['name']}")
            else:
                failed += 1
                print(f"  ✗ {chk['name']}: {chk.get('detail', '')}")

    print(f"\nAcceptance: {passed} passed, {failed} failed")
    if failed > 0:
        sys.exit(1)


def _check_acceptance(result: RunResult, scenario: str) -> list:
    """Run scenario-specific checks."""
    checks = []

    if scenario == "happy-path":
        checks.append({
            "name": "Run completed",
            "ok": result.status == RunStatus.COMPLETED,
            "detail": f"status={result.status.value}",
        })
        checks.append({
            "name": "Message received",
            "ok": len(result.message_parts) > 0,
            "detail": f"{len(result.message_parts)} message parts",
        })
        checks.append({
            "name": "Tool calls tracked",
            "ok": len(result.tool_calls) >= 3,
            "detail": f"{len(result.tool_calls)} tool calls",
        })
        checks.append({
            "name": "Changed files extracted (from diff)",
            "ok": len(result.changed_files) >= 3,
            "detail": f"{len(result.changed_files)} files",
        })
        checks.append({
            "name": "Changed files extracted (from tool output)",
            "ok": len([cf for cf in result.changed_files
                       if any(cf.path.endswith(ext) for ext in ['.py', '.ts', '.js'])]) >= 2,
            "detail": f"files: {[cf.path for cf in result.changed_files]}",
        })
        checks.append({
            "name": "Diff patch available",
            "ok": len(result.diff_patches) > 0,
            "detail": f"{len(result.diff_patches)} diff patches",
        })
        checks.append({
            "name": "Logs generated from tool output",
            "ok": len(result.logs) > 0,
            "detail": f"{len(result.logs)} log entries",
        })
        checks.append({
            "name": "Reasoning blocks captured",
            "ok": len(result.reasoning_blocks) > 0,
            "detail": f"{len(result.reasoning_blocks)} reasoning blocks",
        })
    elif scenario == "failed":
        checks.append({
            "name": "Run failed",
            "ok": result.status == RunStatus.FAILED,
            "detail": f"status={result.status.value}",
        })
        checks.append({
            "name": "Error summary captured",
            "ok": result.error_summary is not None and len(result.error_summary) > 0,
            "detail": f"error={result.error_summary[:50]}",
        })
        checks.append({
            "name": "Tool call tracked with error",
            "ok": any(tc.error for tc in result.tool_calls),
            "detail": f"{sum(1 for tc in result.tool_calls if tc.error)} errors",
        })

    return checks


async def cmd_logs(scenario: str = "happy-path") -> None:
    """Show aggregated logs from fixture events."""
    result = _run_fixture(scenario)
    print(f"=== Logs ({len(result.logs)} entries) ===")
    for log in result.logs:
        level_marker = {"info": " ", "warn": "⚠", "error": "✗"}.get(log.level, " ")
        print(f"  [{log.tool}] {level_marker} {log.message[:120]}")

    print(f"\n=== Tool Calls ({len(result.tool_calls)}) ===")
    for tc in result.tool_calls:
        status_icon = "✗" if tc.error else "✓"
        print(f"  {status_icon} {tc.tool_name} ({tc.duration:.2f}s)")
        if tc.output:
            print(f"      Output: {tc.output[:100]}")


async def cmd_changed_files(scenario: str = "happy-path") -> None:
    """Show changed files from fixture events."""
    result = _run_fixture(scenario)
    if not result.changed_files:
        print("No files changed in this run.")
        return

    print(f"=== Changed Files ({len(result.changed_files)}) ===")
    for cf in result.changed_files:
        icon = {"added": "A", "modified": "M", "deleted": "D"}.get(cf.status, "?")
        plus = f"+{cf.additions}" if cf.additions > 0 else ""
        minus = f"-{cf.deletions}" if cf.deletions > 0 else ""
        print(f"  {icon}  {cf.path:<40} {plus:>5} {minus:>5}")


async def cmd_diff(scenario: str = "happy-path") -> None:
    """Show unified diff from fixture events."""
    result = _run_fixture(scenario)
    if not result.diff_patches:
        print("No diff available for this run.")
        return

    print(f"=== Diff ({len(result.diff_patches)} patches) ===")
    for i, patch in enumerate(result.diff_patches):
        if i > 0:
            print("\n" + "=" * 60)
        # Show first 40 lines per patch
        lines = patch.split("\n")
        shown = lines[:40]
        if len(lines) > 40:
            shown.append(f"... ({len(lines) - 40} more lines)")
        print("\n".join(shown))


# ---------------------------------------------------------------------------
# D1a-local stubs for review / QA reports
#
# These produce a ReviewReport / QAReport with the same fields consumed by
# cmd_ipc's JSON output below. They exist here so bridge_cli remains
# self-contained (no dependency on review_handler / review_cli / cli).
# The real implementations land in executors/review_handler in D1b and
# will replace these.
# ---------------------------------------------------------------------------


def _stub_review_report(main_run_id: str, diff_patch: str) -> ReviewReport:
    """Heuristic stub review report (no executor invocation)."""
    review_run_id = f"review-{main_run_id}-stub"

    findings: List[ReviewFinding] = []

    if "password" in diff_patch.lower() or "secret" in diff_patch.lower() or "api_key" in diff_patch.lower():
        findings.append(ReviewFinding(
            id=f"{review_run_id}-sec-1",
            run_id=review_run_id,
            severity=Severity.HIGH,
            category=FindingCategory.SECURITY,
            title="Potential hardcoded secret",
            description="Diff contains references to 'password', 'secret', or 'api_key'. Verify these are not hardcoded credentials.",
            suggestion="Use environment variables or a secrets manager.",
        ))

    if "SELECT *" in diff_patch or 'f"' in diff_patch or "f'" in diff_patch:
        findings.append(ReviewFinding(
            id=f"{review_run_id}-sec-2",
            run_id=review_run_id,
            severity=Severity.CRITICAL,
            category=FindingCategory.SECURITY,
            title="Potential SQL injection or unsanitized string interpolation",
            description="Diff contains f-strings or SELECT * patterns that may indicate unsanitized input.",
            suggestion="Use parameterized queries or an ORM.",
        ))

    new_files = [l for l in diff_patch.split("\n") if l.startswith("+++ ")]
    test_files = [f for f in new_files if "test" in f.lower()]
    if len(new_files) > len(test_files):
        findings.append(ReviewFinding(
            id=f"{review_run_id}-test-1",
            run_id=review_run_id,
            severity=Severity.MEDIUM,
            category=FindingCategory.TEST_COVERAGE,
            title="New files may lack test coverage",
            description=f"{len(new_files)} files modified, only {len(test_files)} test files found.",
            suggestion="Add tests for new functionality.",
        ))

    if not findings:
        findings.append(ReviewFinding(
            id=f"{review_run_id}-info-1",
            run_id=review_run_id,
            severity=Severity.INFO,
            category=FindingCategory.MAINTAINABILITY,
            title="No obvious issues detected in diff",
            description="Automated heuristic scan found no patterns of concern. Manual review still recommended.",
        ))

    severity_counts = {"critical": 0, "high": 0, "medium": 0, "low": 0, "info": 0}
    for f in findings:
        severity_counts[f.severity.value] += 1

    now = datetime.datetime.now(datetime.timezone.utc)
    return ReviewReport(
        review_run_id=review_run_id,
        status=ReviewStatus.COMPLETED,
        executor="stub",
        total_findings=len(findings),
        critical_count=severity_counts["critical"],
        high_count=severity_counts["high"],
        medium_count=severity_counts["medium"],
        low_count=severity_counts["low"],
        info_count=severity_counts["info"],
        findings=findings,
        started_at=now,
        completed_at=now,
    )


def _stub_qa_report(main_run_id: str, changed_files: List[str]) -> QAReport:
    """Heuristic stub QA report (no executor invocation)."""
    now = datetime.datetime.now(datetime.timezone.utc)
    return QAReport(
        qa_run_id=f"qa-{main_run_id}-stub",
        status=QAStatus.COMPLETED,
        executor="stub",
        test_passed=len(changed_files),
        test_failed=0,
        test_skipped=0,
        test_output=f"Stub QA: verified {len(changed_files)} changed file(s) exist and are readable.",
        risks=[],
        started_at=now,
        completed_at=now,
    )


async def cmd_ipc(action: str, **kwargs) -> None:
    """Simulate IPC commands for Electron bridge testing."""
    if action == "trigger-review":
        # Aggregate diff from fixture
        bridge = RunBridge()
        for e in _fixture_happy_path():
            bridge.ingest(e)
        result = bridge.finalize()
        diff_patch = "\n".join(result.diff_patches) if result.diff_patches else ""
        # Run review via D1a-local stub
        report = _stub_review_report("run-main-001", diff_patch)
        print(json.dumps({
            "action": "review:trigger",
            "run_id": report.review_run_id,
            "status": report.status.value,
            "total_findings": report.total_findings,
            "critical": report.critical_count,
            "high": report.high_count,
            "medium": report.medium_count,
            "low": report.low_count,
            "executor": report.executor,
            "findings": [
                {"severity": f.severity.value, "category": f.category.value, "title": f.title}
                for f in report.findings[:5]
            ],
            "note": "Review run completed via stub heuristic (D1a-local stub, no executor required).",
        }, indent=2))
    elif action == "trigger-qa":
        bridge = RunBridge()
        for e in _fixture_happy_path():
            bridge.ingest(e)
        result = bridge.finalize()
        changed_files = [cf.path for cf in result.changed_files]
        report = _stub_qa_report("run-main-001", changed_files)
        print(json.dumps({
            "action": "qa:trigger",
            "run_id": report.qa_run_id,
            "status": report.status.value,
            "test_passed": report.test_passed,
            "test_failed": report.test_failed,
            "test_skipped": report.test_skipped,
            "executor": report.executor,
            "note": "QA run completed via stub (D1a-local stub, no executor required).",
        }, indent=2))
    elif action == "continue":
        thread_id = kwargs.get("thread_id", "thread-001")
        print(json.dumps({
            "action": "run:continue",
            "request": {"thread_id": thread_id, "prompt": "Fix the review findings", "previous_run_id": "run-happy-001"},
            "response": {"run_id": f"run-continue-{thread_id}"},
            "note": "New run created with conversation history from previous run.",
        }, indent=2))
    elif action == "retry":
        thread_id = kwargs.get("thread_id", "thread-001")
        print(json.dumps({
            "action": "run:retry",
            "request": {"thread_id": thread_id, "prompt": "Refactor auth module"},
            "response": {"run_id": f"run-retry-{thread_id}", "run_seq": 2},
            "note": "New run created WITHOUT history (fresh start).",
        }, indent=2))
    else:
        print(f"Unknown IPC action: {action}. Valid: trigger-review, trigger-qa, continue, retry", file=sys.stderr)
        sys.exit(1)


# ---------------------------------------------------------------------------
# Entry point
# ---------------------------------------------------------------------------


async def handle_bridge_command(args) -> None:
    """Dispatch bridge subcommands."""
    sub = args.bridge_subcommand
    if sub is None:
        print("Usage: bridge {accept|logs|changed-files|diff|ipc} [...]", file=sys.stderr)
        sys.exit(1)

    if sub == "accept":
        await cmd_accept(scenario=getattr(args, "scenario", "all"))
    elif sub == "logs":
        await cmd_logs(scenario=getattr(args, "fixture", "happy-path"))
    elif sub == "changed-files":
        await cmd_changed_files(scenario=getattr(args, "fixture", "happy-path"))
    elif sub == "diff":
        await cmd_diff(scenario=getattr(args, "fixture", "happy-path"))
    elif sub == "ipc":
        await cmd_ipc(
            action=getattr(args, "ipc_action", ""),
            main_run_id=getattr(args, "main_run_id", "run-main-001"),
            thread_id=getattr(args, "thread_id", "thread-001"),
        )
    else:
        print(f"Unknown bridge command: {sub}", file=sys.stderr)
        sys.exit(1)
